#!/bin/bash

# Check if Pandoc is installed
if ! command -v pandoc &> /dev/null; then
  echo "Pandoc is not installed. Please install Pandoc to continue."
  exit 1
fi

# Optional: Check if LaTeX engine is installed
if ! command -v xelatex &> /dev/null; then
  echo "Warning: xelatex not found. PDF export may fail. Install MacTeX/TeX Live or use --pdf-engine=pdflatex."
fi

# Create the book markdown
cat <<EOF > book.md
---
title: "Web3 Open Risk Framework"
author: "Treno Solutions"
date: "$(date +%Y-%m-%d)"
---

# Web3 Open Risk Framework

> This book compiles the core documentation of the Web3 Open Risk Framework. For the latest version, visit the official repository.

\newpage

# Table of Contents

<!-- The table of contents will be generated by Pandoc with --toc -->

\newpage

# 1. Introduction
EOF

cat README.md philosophy.md methodology.md categories.md types.md scopes.md objectives.md owners.md risk.md indicator.md measure.md assessment.md terminology.md >> book.md

# Create the PDF
pandoc book.md -o risk-framework.pdf --toc --pdf-engine=xelatex

if [ $? -eq 0 ]; then
  echo "Done! The PDF is under risk-framework.pdf."
  rm book.md
else
  echo "Error creating the PDF. Check Pandoc and LaTeX installation."
fi 