#!/bin/bash

# Check if Pandoc is installed
if ! command -v pandoc &> /dev/null; then
  echo "Pandoc is not installed. Please install Pandoc to continue."
  exit 1
fi

# Optional: Check if LaTeX engine is installed
if ! command -v xelatex &> /dev/null; then
  echo "Warning: xelatex not found. PDF export may fail. Install MacTeX/TeX Live or use --pdf-engine=pdflatex."
fi

# Create the book markdown
cat <<EOF > framework-book.md
---
title: "Web3 Open Risk Framework"
subtitle: "A Comprehensive Guide to Web3 Risk Assessment"
author: "Benjamin Damm"
date: "$(date +%Y-%m-%d)"
version: "1.0"
documentclass: book
geometry: "a4paper,margin=2.4cm"
fontsize: 11pt
toc: true
toc-depth: 2
---

\newpage

EOF

# Add front matter (title page, copyright, preface)
awk 'BEGIN{inheader=0} /^---/ {inheader = !inheader; next} !inheader {print}' front-matter.md >> framework-book.md

echo -e "\n\`\`\`{=latex}\n\\\\pagebreak\n\`\`\`\n" >> framework-book.md

echo -e "\n## Table of Contents\n" >> framework-book.md
echo -e "<!-- The table of contents will be generated by Pandoc with --toc -->\n" >> framework-book.md

echo -e "\n\`\`\`{=latex}\n\\\\pagebreak\n\`\`\`\n" >> framework-book.md

echo -e "\n# 1. Framework\n" >> framework-book.md

# Insert module files, remove YAML headers, keep headings unchanged
for file in ../README.md ../philosophy.md ../methodology.md ../categories.md ../types.md ../scopes.md ../objectives.md ../owners.md ../risk.md ../indicator.md ../measure.md ../assessment.md; do
  awk 'BEGIN{inheader=0} /^---/ {inheader = !inheader; next} !inheader {print}' "$file" >> framework-book.md
done

echo -e "\n# 2. Glossary\n" >> framework-book.md
awk 'BEGIN{inheader=0} /^---/ {inheader = !inheader; next} !inheader {print}' ../terminology.md >> framework-book.md

echo -e "\n\`\`\`{=latex}\n\\\\pagebreak\n\`\`\`\n" >> framework-book.md

echo -e "\n# 3. Afterword\n" >> framework-book.md
awk 'BEGIN{inheader=0} /^---/ {inheader = !inheader; next} !inheader {print}' afterword.md >> framework-book.md

# Remove emojis and non-ASCII characters
LC_ALL=C tr -cd '\11\12\15\40-\176' < framework-book.md > framework-book-ascii.md
mv framework-book-ascii.md framework-book.md

# Remove leading and trailing spaces from \pagebreak lines so Pandoc recognizes them as page breaks
sed -i '' -E 's/^ *\\\\pagebreak *$/\\\\pagebreak/' framework-book.md  # macOS BSD sed
# For Linux use instead:
# sed -i -E 's/^ *\\\\pagebreak *$/\\\\pagebreak/' framework-book.md

# Create the PDF
pandoc framework-book.md -o risk-framework.pdf --toc --toc-depth=2 --pdf-engine=xelatex -V geometry:"a4paper,margin=2.4cm" -V fontsize=11pt -V tables=yes --variable booktabs=true

if [ $? -eq 0 ]; then
  echo "Done! The PDF is under risk-framework.pdf."
  rm framework-book.md
else
  echo "Error creating the PDF. Check Pandoc and LaTeX installation."
fi 